"""
Utility functions for providing Mazo research context to agents.
"""

from src.graph.state import AgentState


def get_mazo_research_context(state: AgentState, ticker: str) -> str:
    """
    Extract Mazo research from state and format it for inclusion in agent prompts.
    
    Args:
        state: The AgentState containing Mazo research
        ticker: The ticker symbol to get research for
        
    Returns:
        A formatted string containing Mazo research, or empty string if not available
    """
    mazo_research = state.get("data", {}).get("mazo_research")
    
    if not mazo_research:
        return ""
    
    if not isinstance(mazo_research, dict):
        return ""
    
    # Check if research is for this ticker
    research_ticker = mazo_research.get("ticker")
    if research_ticker != ticker:
        return ""
    
    research_text = mazo_research.get("research")
    if not research_text:
        return ""
    
    # Truncate to reasonable length (first 2000 chars) to avoid token limits
    truncated_research = research_text[:2000]
    if len(research_text) > 2000:
        truncated_research += "... [truncated]"
    
    return f"""
MAZO RESEARCH CONTEXT (Supplementary Information):
The following research report was generated by Mazo, our deep research agent. 
This provides comprehensive fundamental analysis, competitive positioning, risk 
factors, and market insights that you may find useful.

{truncated_research}

CRITICAL: This research is supplementary context only. You MUST:
1. Maintain your own unique analytical framework and investment philosophy
2. Apply your own specific criteria and decision-making process
3. Use your own voice, style, and perspective in your reasoning
4. Consider this research as additional data points, not a replacement for your analysis
5. If the research conflicts with your framework, prioritize your own judgment

The research should ENHANCE your analysis, not change who you are as an analyst.
Your unique perspective and methodology are what make your signal valuable.
"""


def has_mazo_research(state: AgentState, ticker: str) -> bool:
    """
    Check if Mazo research is available for a given ticker.
    
    Args:
        state: The AgentState containing Mazo research
        ticker: The ticker symbol to check
        
    Returns:
        True if Mazo research is available for this ticker, False otherwise
    """
    mazo_research = state.get("data", {}).get("mazo_research")
    if not mazo_research or not isinstance(mazo_research, dict):
        return False
    
    research_ticker = mazo_research.get("ticker")
    research_text = mazo_research.get("research")
    
    return research_ticker == ticker and bool(research_text)
